name: Build  
  
on: [push, pull_request]  
  
jobs:  
  build_wheels:  
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  
    steps:  
    - uses: actions/checkout@v4
    
    # Used to host cibuildwheel
    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: OPT4TorchDataSet-${{ matrix.os }}
        path: ./wheelhouse/*.whl